Add --nodes-per-rank option to tester
nv-legate/legate.core pull request #749
Opened 2023-06-05 19:11 UTC by bryevdv

This PR adds support for `--node-per-rank` to `legate.tester`

2023-06-05 23:22 UTC, manopapad requested changes
Mostly nits, and what looks like one double-counting of `config.ranks` in GPU phase `compute_spec`.

2023-06-06 16:42 UTC, bryevdv commented on legate/tester/stages/_linux/gpu.py
> +        return StageSpec(workers, shards * workers)
This change results in two additional shards, just confirming that's what you what?
```
E         Left contains 2 more items, first extra item: Shard(ranks=[(0, 1), (2, 3)])
E         Full diff:
E           [
E            Shard(ranks=[(0, 1), (2, 3)]),
E            Shard(ranks=[(0, 1), (2, 3)]),
E         +  Shard(ranks=[(0, 1), (2, 3)]),
E         +  Shard(ranks=[(0, 1), (2, 3)]),...
```

2023-06-06 19:01 UTC, manopapad commented on legate/tester/stages/_linux/gpu.py
> +        return StageSpec(workers, shards * workers)
I just tried a simple test, and I think this change, and the one from `int(degree * oversub_factor / config.ranks)` to `degree * oversub_factor`, is correct. Can you fact-check me?

I made a sample machine with 4 GPUs with 3GB framebuff each:

```
       return (GPUInfo(0, 3 * (1 << 30)),
               GPUInfo(1, 3 * (1 << 30)),
               GPUInfo(2, 3 * (1 << 30)),
               GPUInfo(3, 3 * (1 << 30)))
```

In this case, for ` --fbmem 1000 --gpus 1 --ranks-per-node 2` I think there should be 4 workers; two using GPUs 0 and 1 for their two ranks, and two using GPUs 2 and 3, given that each only uses 1.5GB (with bloat factor) of the available 3GB.

Here's what I see with the original code:

```
~/cunumeric> ./test.py --dry-run --use cuda --fbmem 1000 --gpus 1 --ranks-per-node 2
N = 4
degree = 2
fbsize = 3072.0
oversub_factor = 2
workers = 2
shards * oversub_factor = [Shard(ranks=[(0,), (1,)]), Shard(ranks=[(2,), (3,)]), Shard(ranks=[(0,), (1,)]), Shard(ranks=[(2,), (3,)])]
shards * workers = [Shard(ranks=[(0,), (1,)]), Shard(ranks=[(2,), (3,)]), Shard(ranks=[(0,), (1,)]), Shard(ranks=[(2,), (3,)])]
```

And here's what I get after replacing `int(degree * oversub_factor / config.ranks)` with `degree * oversub_factor`:

```
~/cunumeric> ./test.py --dry-run --use cuda --fbmem 1000 --gpus 1 --ranks-per-node 2
N = 4
degree = 2
fbsize = 3072.0
oversub_factor = 2
workers = 4
shards * oversub_factor = [Shard(ranks=[(0,), (1,)]), Shard(ranks=[(2,), (3,)]), Shard(ranks=[(0,), (1,)]), Shard(ranks=[(2,), (3,)])]
shards * workers = [Shard(ranks=[(0,), (1,)]), Shard(ranks=[(2,), (3,)]), Shard(ranks=[(0,), (1,)]), Shard(ranks=[(2,), (3,)]), Shard(ranks=[(0,), (1,)]), Shard(ranks=[(2,), (3,)]), Shard(ranks=[(0,), (1,)]), Shard(ranks=[(2,), (3,)])]
```

So it appears that `shards * oversub_factor` is sufficient for the return value as well.

2023-06-06 20:45 UTC, bryevdv commented
@manopapad I pushed changes for OMP let me know if this matches intent

2023-06-07 01:21 UTC, manopapad requested changes

2023-06-07 01:21 UTC, manopapad commented on legate/tester/stages/_linux/omp.py
>              ]
```suggestion
            ]
        if config.ranks > 1:
            args += [
                "--ranks-per-node",
                str(config.ranks),
            ]
```

Doesn't look like `--ranks-per-node` is added in this path.

2023-06-07 19:17 UTC, manopapad approved these changes
LGTM. The CI failures are unrelated, and can be ignored.

2023-06-07 20:53 UTC, merged