Set lib_dir explicitly to lib/, even on RHEL
nv-legate/legate.core pull request #766
Opened 2023-06-21 05:56 UTC by manopapad

Works around https://github.com/nv-legate/cunumeric/issues/835 until https://github.com/rapidsai/rapids-cmake/issues/426 is addressed.

Also take this opportunity to bump rapids-cmake version.

2023-06-22 23:39 UTC, trxcllnt commented on legate_core_cpp.cmake
> +set(CMAKE_INSTALL_LIBDIR "lib")
```suggestion
if(TARGET conda_env)
  set(CMAKE_INSTALL_LIBDIR "lib")
endif()
```

2023-06-22 23:40 UTC, trxcllnt commented on legate_core_python.cmake
> +
```suggestion
# ############################################################################
# * conda environment --------------------------------------------------------
rapids_cmake_support_conda_env(conda_env)

# We're building python extension libraries, which must always be installed
# under lib/, even if the system normally uses lib64/. Rapids-cmake currently
# doesn't realize this when we're going through scikit-build, see
# https://github.com/rapidsai/rapids-cmake/issues/426
if(TARGET conda_env)
  set(CMAKE_INSTALL_LIBDIR "lib")
endif()

```

2023-06-22 23:41 UTC, trxcllnt requested changes
Left similar suggestions as in https://github.com/nv-legate/cunumeric/pull/971

2023-06-24 02:06 UTC, manopapad commented
@bryevdv I have verified that this and https://github.com/nv-legate/cunumeric/pull/971 work properly on an RHEL container, lmk when you get to try them on Perlmutter.

2023-06-26 21:33 UTC, bryevdv commented
@manopapad I tried both of these PRs (rebased locally on latest `branch-23.07`) on perlmutter and everything worked

2023-06-26 23:42 UTC, merged